#!/bin/sh
# unused examples

upgrade_to_ten_one() {
    env PAGER=cat freebsd-update upgrade -r 10.1-RELEASE
}

update_to_latest_patch() {
    env PAGER=cat freebsd-update fetch install
}

zfs_no_setuid() {
    ########## prevents a periodic job from searching for suid in large dataset
    zfs set setuid=off tank/largebackupdataset
}

mfsbsd_install() {
    ########## if using mfsbsd special edition
    mount_cd9660 /dev/cd0 /cdrom || mount -o ro /dev/da0a /cdrom
    zfsinstall -d $DISK -u /cdrom/10.1-RELEASE-amd64 -p $POOLNAME -s 2G -z 2G -c
}

fzg_mirror() {
    fzg -d ada0 -d ada1 -z 5g -m -r mirror -H `hostname-by-etc-hosts` -D
    fzg -d ada0 -d ada1 -z 5g    -r mirror -H `hostname-by-ptr-dns`
}

fzg_single() {
    fzg -d ada0         -z 5g -m           -H `hostname-by-etc-hosts` -D
    fzg -d ada0         -z 5g              -H `hostname-by-ptr-dns`
}

fzg_usb() {
    fzg -d da0          -z 5g -m           -H usb.local -p usb        -n -q
    fzg -d da0          -z 5g              -H usb.local -p usb        -n
}

fzg_attach_disk() {
    fzg -e ada0 -z 5g -p $POOLNAME -d ada1
}

fzg_mfsroot_update() {
    fzg -f -p $POOLNAME
}

fzg_tank_mirror() {
    fzg-random-key
    fzg -i -z 922 -p tank -r mirror -d ada0 -d ada1 -d ada2
    fzg-unlock-on-boot
}

fzg_priv_mirror() {
    rm /boot/data.crypt.key
    fzg -i -t 6 -d ada0 -d ada1 -p priv
}

fzg_priv_lock() {
    fzg -l -p priv
}

fzg_priv_unlock() {
    fzg -u -p priv -d ada0p6 -d ada1p6
}

jail_help() {
    ioc-setup
    ioc-newtemplate common 'lo1|10.7.7.253/32'
    ioc-newjail common jailname 'lo1|10.7.7.253/32'
    iocage set boot=off jailname
    iocage start jailname
    iocage stop jailname
    icoage destroy -f jailname
    ########## deploy
    # vi local/cshvars
    # source local/cshvars
    # _deploy_jails good
}

things_to_sync() {
    cat <<EOF
########## Things that are similar globally
    /boot/loader.conf
    /etc/ssh/sshd_config
    /root/.ssh/authorized_keys
    /root/bin/
    /root/git/
    /root/perm/
    /usr/home/urep/
########## Things that are similar per DC across mfs types
    /boot/packages/
    /boot/resolv.conf.append
    /boot/resolv.conf.overwrite
    /boot/periodic.conf.append
    /boot/periodic.conf.overwrite
    /boot/sysctl.conf.append
    /boot/sysctl.conf.overwrite
    /boot/hosts.append
    /boot/hosts.overwrite
    /etc/hosts
########## Things that are unique per system/jail
    /boot/../mfsroot    #because of /boot is symlink to POOLNAME/boot
    /boot/*eli
    /boot/*key
    /boot/fstab.append
    /boot/loader.conf.local
    /boot/zfs/
    /etc/*db
    /etc/*passwd
    /etc/fstab
    /etc/group
    /etc/hostid
    /etc/mail
    /etc/pf/
    /etc/rc.conf.d/
    /etc/shells
    /etc/ssh/
    /root/.ssh/authorized_keys2
    /root/crontabbed/
    /root/local/
EOF
}

# IP_net_suffix name boot=on_or_off

setenv  JAILSGOOD '\
6   dtfc                off \
251 buildercouchbasepkg off \
'

setenv  JAILSDEV '\
22  echoplexus  off \
24  gitannex    off \
9   gitlab      off \
26  gogs        off \
28  phabricator off \
30  pydio       off \
'

setenv  JAILSBAD '\
36  baikal    off \
38  couchdtfc off \
40  horde     off \
'

# minidlna and firefly have trouble getting multicast from jails
